name: "It's my life"
favicon: null
layout_spectrum: 0
typography_spectrum: 0.09856631
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "It's My Digital Life"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#6D665C'
    - '#A3A29A'
    - '#161616'
    - '#533A1F'
  brandStrength: 0.125
  lightness: 0.8297491
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
