collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.09856631
color:
  saturation: 0.937276
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#6D665C'
    - '#A3A29A'
    - '#161616'
    - '#533A1F'
  rhythmicContrast: 0.5752688
layout_spectrum: 0.2293907
name: "It's my life"
